name: Enable auto-merge for trusted PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-auto-merge:
    if: >-
      github.event.pull_request.user.login == 'MikkoParkkola' ||
      github.actor == 'MikkoParkkola' ||
      contains(join(github.event.pull_request.labels.*.name, ','), 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

