name: Auto-approve trusted PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  auto-approve:
    if: >-
      github.event.pull_request.user.login == 'MikkoParkkola' ||
      github.actor == 'MikkoParkkola' ||
      contains(join(github.event.pull_request.labels.*.name, ','), 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve
        uses: hmarr/auto-approve-action@v4
        with:
<<<<<<< HEAD
          review-message: 'Auto-approving trusted author PR'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
          review-message: "Auto-approving trusted author PR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

>>>>>>> 87a361b (ci: split CI into build/tests/lint and rename workflow to 'Node CI')
