name: Publish Docker image

on:
push:
  branches: [main]
  tags: ['v*']
workflow_dispatch:
  inputs:
    version:
      description: 'Version tag to publish (e.g., v1.1.0). Leave empty to use package.json or tag ref.'
      required: false
      type: string

jobs:
docker:
  runs-on: ubuntu-latest
  permissions:
    contents: read
    packages: write
  steps:
    - uses: actions/checkout@v4
    - name: Extract version and image name
      shell: bash
      run: |
        if [[ -n "${{ github.event.inputs.version }}" ]]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        else
          REF_NAME="${GITHUB_REF##*/}"
          if [[ "${GITHUB_REF_TYPE}" == "tag" && "${REF_NAME}" == v* ]]; then
            echo "VERSION=${REF_NAME}" >> $GITHUB_ENV
          else
            echo "VERSION=v$(jq -r '.version' package.json)" >> $GITHUB_ENV
          fi
        fi
        echo "IMAGE_NAME=ghcr.io/$(echo \"$GITHUB_REPOSITORY\" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          ${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.IMAGE_NAME }}:latest
