name: prerelease-binaries

on:
  push:
    branches: [main]

jobs:
  build-sea:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Build dist
        run: npm run build
      - name: Build SEA (macOS)
        if: startsWith(matrix.os, 'macos')
        run: npm run make:macos:sea
      - name: Build SEA (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: npm run make:linux:sea
      - name: Build SEA (Windows)
        if: startsWith(matrix.os, 'windows')
        run: npm run make:windows:sea
      - name: Package artifact
        shell: bash
        run: |
          set -euo pipefail
          OS_NAME="${{ matrix.os }}"
          if [[ "$OS_NAME" == macos* ]]; then OS=macos; EXT=tar.gz; BIN=build/beepermcp.sea.run; ARCH=$(uname -m); fi
          if [[ "$OS_NAME" == ubuntu* ]]; then OS=linux; EXT=tar.gz; BIN=build/beepermcp.sea.run; ARCH=$(uname -m); fi
          if [[ "$OS_NAME" == windows* ]]; then OS=windows; EXT=zip; BIN=build/beepermcp.sea.run.exe; ARCH=${PROCESSOR_ARCHITECTURE:-AMD64}; fi
          case "$ARCH" in
            x86_64|AMD64) ARCH_OUT=x64 ;;
            arm64|aarch64|ARM64) ARCH_OUT=arm64 ;;
            *) ARCH_OUT=$ARCH ;;
          esac
          NAME="agentsmcp-${OS}-${ARCH_OUT}"
          mkdir -p artifacts
          if [[ "$OS" == windows ]]; then
            mkdir -p pkg && cp "$BIN" pkg/agentsmcp.exe
            (cd pkg && zip -q "../artifacts/${NAME}.zip" agentsmcp.exe)
          else
            mkdir -p pkg && cp "$BIN" pkg/agentsmcp && chmod +x pkg/agentsmcp
            tar -czf "artifacts/${NAME}.tar.gz" -C pkg agentsmcp
          fi
          ls -l artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: agentsmcp-${{ runner.os }}
          path: artifacts/*
  prerelease:
    needs: build-sea
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: agentsmcp-*
          path: artifacts
          merge-multiple: true
      - name: Compute checksums and manifest
        run: |
          cd artifacts
          ls -l
          sha256sum agentsmcp-*.*z* > checksums.txt || shasum -a 256 agentsmcp-*.*z* > checksums.txt
          node -e '
            const fs=require("fs");
            const cp=(n)=>fs.existsSync(n)?fs.statSync(n).size:0;
            const files=fs.readdirSync(".").filter(f=>f.startsWith("agentsmcp-")&&(f.endsWith(".tar.gz")||f.endsWith(".zip")));
            const txt=fs.readFileSync("checksums.txt","utf8");
            const getSha=(n)=> (txt.split(/\n/).find(l=>l.includes(n))||"").split(/[\s]+/)[0];
            const version=(process.env.GITHUB_SHA||"").slice(0,7);
            const assets=files.map(name=>({name, size:cp(name), sha256:getSha(name)}));
            fs.writeFileSync("manifest.json", JSON.stringify({version, assets}, null, 2));
          '
          cd -
      - name: Sign manifest (optional ed25519 JSON signature)
        if: ${{ secrets.MANIFEST_PRIVKEY_B64 != '' }}
        run: |
          cd artifacts
          node -e '
            const fs=require("fs");
            const crypto=require("crypto");
            const b64=process.env.MANIFEST_PRIVKEY_B64||"";
            if(!b64) process.exit(0);
            const key=crypto.createPrivateKey({key:Buffer.from(b64,"base64"), format:"der", type:"pkcs8"});
            const data=fs.readFileSync("manifest.json");
            const sig=crypto.sign(null, data, key).toString("base64");
            const out={alg:"ed25519", sig};
            fs.writeFileSync("manifest.sig", JSON.stringify(out));
          '
          cd -
      - name: Create prerelease
        uses: softprops/action-gh-release@v2
        with:
          tag_name: prerelease-${{ github.sha }}
          prerelease: true
          files: |
            artifacts/agentsmcp-*.*z*
            artifacts/checksums.txt
            artifacts/manifest.json
            artifacts/manifest.sig
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

