name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate release notes
        id: notes
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          if [ -f CHANGELOG.md ]; then
            awk 'BEGIN{p=0} /^## /{ if(p) exit; if($0 ~ /'"$TAG"'/) p=1 } p' CHANGELOG.md > RELEASE_NOTES.md || true
          fi
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.notes.outputs.tag }}
          name: ${{ steps.notes.outputs.tag }}
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

