name: release-binaries

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: |
          npm ci
      - name: Build dist
        run: |
          npm run build
      - name: Package binaries (x64 + macOS arm64)
        run: |
          npx pkg -t node22-macos-x64,node22-macos-arm64,node22-linux-x64,node22-win-x64 --compress Brotli \
            --output build/beepermcp dist/src/bin.js
          # pkg writes single output when one target; for multiple, it appends platform suffixes
          ls -l build
      - name: Arrange artifacts in descriptive subfolders and compute checksums/manifest
        run: |
          mkdir -p artifacts
          # Create descriptive folders and rename executables to `agentsmcp`
          mkdir -p artifacts/macos/x64 artifacts/macos/arm64 artifacts/linux/x64 artifacts/windows/x64
          mv build/beepermcp-macos-x64 artifacts/macos/x64/agentsmcp
          mv build/beepermcp-macos-arm64 artifacts/macos/arm64/agentsmcp
          mv build/beepermcp-linux-x64 artifacts/linux/x64/agentsmcp
          mv build/beepermcp-win-x64.exe artifacts/windows/x64/agentsmcp.exe || true
          # Ensure executables are +x on Unix platforms
          chmod +x artifacts/macos/x64/agentsmcp || true
          chmod +x artifacts/macos/arm64/agentsmcp || true
          chmod +x artifacts/linux/x64/agentsmcp || true
          # Package each folder as an archive for GitHub release assets
          cd artifacts
          tar -czf agentsmcp-macos-x64.tar.gz -C macos/x64 agentsmcp
          tar -czf agentsmcp-macos-arm64.tar.gz -C macos/arm64 agentsmcp
          tar -czf agentsmcp-linux-x64.tar.gz -C linux/x64 agentsmcp
          (cd windows/x64 && zip -q ../../agentsmcp-windows-x64.zip agentsmcp.exe) || true
          # Compute checksums for archives
          sha256sum agentsmcp-*.*z* > checksums.txt || shasum -a 256 agentsmcp-*.*z* > checksums.txt
          node -e '
            const fs=require("fs");
            const cp=(n)=>fs.existsSync(n)?fs.statSync(n).size:0;
            const txt=fs.readFileSync("checksums.txt","utf8");
            const getSha=(n)=> (txt.split(/\n/).find(l=>l.includes(n))||"").split(/[\s]+/)[0];
            // Prefer GITHUB_REF_NAME (e.g., v1.2.3), fallback to short SHA
            const ref=process.env.GITHUB_REF_NAME||"";
            const version=(ref.startsWith("v")?ref.slice(1):ref)|| (process.env.GITHUB_SHA||"").slice(0,7);
            const assets=[
              {name:"agentsmcp-macos-x64.tar.gz", platform:"macos-x64"},
              {name:"agentsmcp-macos-arm64.tar.gz", platform:"macos-arm64"},
              {name:"agentsmcp-linux-x64.tar.gz", platform:"linux-x64"},
              {name:"agentsmcp-windows-x64.zip", platform:"win-x64"}
            ].filter(a=>fs.existsSync(a.name)).map(a=>({name:a.name, platform:a.platform, size:cp(a.name), sha256:getSha(a.name)}));
            fs.writeFileSync("manifest.json", JSON.stringify({version, assets}, null, 2));
          '
          cd -
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: beepermcp-binaries
          path: artifacts/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: beepermcp-binaries
          path: artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/agentsmcp-macos-x64.tar.gz
            artifacts/agentsmcp-macos-arm64.tar.gz
            artifacts/agentsmcp-linux-x64.tar.gz
            artifacts/agentsmcp-windows-x64.zip
            artifacts/checksums.txt
            artifacts/manifest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
